@TodoApi_HostAddress = https://localhost:10002

GET {{TodoApi_HostAddress}}/todos/test234
Accept: application/json

###

POST {{TodoApi_HostAddress}}/todos
Content-Type: application/json
Accept: application/json

{
  "name": "test",
  "todos": [
    {
      "name": "Test Todo1",
      "completed": false
    },
    {
      "name": "Test Todo2",
      "completed": false
    }
  ]
}

###
